include theos/makefiles/common.mk
export ARCHS = armv7 arm64
TWEAK_NAME = MSettings-App
MSettings-App_FILES = MSettings-App.xm
MSettings-App_FRAMEWORKS = UIKit Foundation

include $(THEOS_MAKE_PATH)/tweak.mk
